### ISSUE TITLE
ImproperlyConfigured: `PATH` is not a valid setting

### ISSUE THREAD

**Issue by johnchase** [sondrelg/django-swagger-tester#40]
Thanks for this the work on this repo, I have been looking for something like this for Django for sometime.

When running tests with `django-swagger-tester` I am getting the following error:

```python
Found an excess key in the SWAGGER_TESTER settings: `PATH`.
System check identified no issues (0 silenced).
E
======================================================================
ERROR: documentation.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: documentation.tests
Traceback (most recent call last):
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/unittest/loader.py", line 436, in _find_test_path                                                                             
    module = self._get_module_from_name(name)
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name                                                                       
    __import__(name)
  File "/Users/johnchase/biota/documentation/documentation/tests.py", line 3, in <module>
    from django_swagger_tester.response_validation.static_schema import validate_response
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/site-packages/django_swagger_tester/response_validation/static_schema.py", line 10, in <module>                               
    from django_swagger_tester.response_validation.base.base import SwaggerTestBase
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/site-packages/django_swagger_tester/response_validation/base/base.py", line 8, in <module>                                    
    from django_swagger_tester.response_validation.base.swagger_tester import SwaggerTester
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/site-packages/django_swagger_tester/response_validation/base/swagger_tester.py", line 5, in <module>                          
    from django_swagger_tester.configuration import settings
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/site-packages/django_swagger_tester/configuration.py", line 59, in <module>                                                   
    settings = SwaggerTesterSettings()
  File "/Users/johnchase/miniconda3/envs/doc-api/lib/python3.7/site-packages/django_swagger_tester/configuration.py", line 32, in __init__                                                   
    raise ImproperlyConfigured(f"`{setting}` is not a valid setting for the django-swagger-tester module")                                                                                   
django.core.exceptions.ImproperlyConfigured: `PATH` is not a valid setting for the django-swagger-tester module   
```     

Here is my `settings.py`
```python
SWAGGER_TESTER = {
    "CASE": "camel case",
    "PATH": "/Users/johnchase/Desktop/v1.yaml",
}  # not required for drf_yasg
```

And my test:
```
class TestNothin(BaseViewTest):
    """Test class for nothing."""

    def test_get_200(self):
        """Verifies that a 200 is returned for a valid GET request to the /test/ endpoint."""
        response = self.client.get("/test/")
       # Test Swagger documentation
        validate_response(response=response, method="GET", endpoint_url="/test/")
```

running `python manage.py test` throws the error. I checked the demo app in this repository and received the same error.

Adding `self.PATH` on line 19 in the `configuration.py` file: https://github.com/sondrelg/django-swagger-tester/blob/aacde4d5b80326a9d4155a49936dcfaea27a14cf/django_swagger_tester/configuration.py#L19 fixes the issue and it works perfectly. I may be missing something, though I would be happy to submit a pr if that is all it is.

**Comment by sondrelg** [comment]
There are currently 2 different `validate_response` functions - which one are you using?

**Comment by sondrelg** [comment]
No need to answer the above question - I see you are right in that it has not been included as a setting after the last rewrite. I'm adding it back now :)

**Comment by sondrelg** [comment]
Feel free to test using the input branch to verify, otherwise I'll try and push a new version tomorrow anyways.

**Comment by johnchase** [comment]
Thanks @sondrelg! Testing with the input branch, everything is working as expected
